jackmpcollins/magentic

README.md, examples/quiz/quiz_async.py, poetry.lock, pyproject.toml, src/magentic/chat_model/openai_chat_model.py, src/magentic/prompt_chain.py, src/magentic/prompt_function.py, tests/test_prompt_function.py
Enable the `@prompt` decorator to work with `async` functions.
To enable this, add an `AsyncPromptFunction` class and the `OpenaiChatModel.acomplete` method. Add `async_quiz.py` example to demonstrate why this is useful.
This PR does not add support for async FunctionCalls.
Also, replace some type ignore comments with `cast`
=> Support async prompt functions

README.md, src/magentic/prompt_chain.py, src/magentic/prompt_function.py, tests/test_chat.py, tests/test_prompt_function.py
Remove ability to use function docstring as template
- Do not use docstring as template
- Convert tests to use template arg instead of docstring
- Update README type hints examples to use template not docstring
=> Remove ability to use function docstring as template

src/magentic/chat_model/openai_chat_model.py, tests/test_prompt_function.py
Raise a `StructuredOutputError` from a `ValidationError` when parsing model output. This provides a more helpful error message.
previously
```
ValidationError: 1 validation error for Output[int]
Invalid JSON: expected value at line 2 column 12 [type=json_invalid, input_value='{\n  "value": (new Date(...1000 * 60 * 60 * 24)\n}', input_type=str]
For further information visit https://errors.pydantic.dev/2.0.3/v/json_invalid
```
now
```
StructuredOutputError: Failed to parse model output '{ "value": (new Date(\'2019-07-03\') - new Date(\'2019-01-04\')) / (1000 * 60 * 60 * 24) }'. You may need to update your prompt to encourage the model to return a specific type.
```
=> Raise StructuredOutputError from ValidationError to clarify error

README.md, src/magentic/__init__.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/streamed_str.py, tests/test_prompt_function.py, tests/test_streamed_str.py
Add support for streaming string output. Now all responses from the openai api are streamed internally but converted to regular strings and objects unless a `StreamedStr` or `AsyncStreamedStr` was specifically requested.
Commits
- Add `StreamedStr` class
- Enable using `StreamedStr` with `.complete` method
- Add `AsyncStreamedStr`
- Enable using `AsyncStreamedStr` with `.acomplete` method
- Add Streaming section to README
---
> ### Streaming
>
> The `StreamedStr` (and `AsyncStreamedStr`) class can be used to stream the output of the LLM. This allows you to process the text while it is being generated, rather than receiving the whole output at once. Multiple `StreamedStr` can be created at the same time to stream LLM outputs concurrently. In the below example, generating the description …
=> Add streaming for string output

README.md, src/magentic/streamed_str.py, tests/test_streamed_str.py
- Subclass collections.abc for StreamedStr. Rename generator -> chunks
- Add async_iter function and use to simplify tests
- Improve and add timing to StreamedStr example in README
=> Tidy StreamedStr type hints. Improve README example.

README.md, tests/test_function_call.py, tests/test_prompt_function.py
`FunctionCall` works with coroutine functions with no changes. Add tests to confirm this. Also add a note to the README.
=> Add test for async/coroutine function with FunctionCall

.pre-commit-config.yaml, pyproject.toml, src/magentic/chat_model/openai_chat_model.py, src/magentic/typing.py, tests/test_function_call.py, tests/test_openai_chat_model.py, tests/test_streaming.py, tests/test_typing.py
- Enable flake8-errmsg
- Enable pygrep-hooks
- Enable Ruff-specific rules. Update pre-commit
- Enable tryceratops
- Ignore flake8-print just for examples/ dir
- Enable flake8-pytest-style
- Ignore flake8-bandit only for tests
=> Enable more linting rules with Ruff. Update pre-commit hooks

src/magentic/chat.py, src/magentic/chat_model/base.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/prompt_chain.py, tests/test_chat.py, tests/test_prompt_chain.py
- Enable async functions to be used with `@prompt_chain`
- Add `Chat.exec_function_call`, `Chat.aexec_function_call`, `Chat.asubmit` methods
- Delete `FunctionCallMessage` and remove usage from openai_chat_model
---
```python
from magentic import prompt_chain
async def get_current_weather(location, unit="fahrenheit"):
"""Get the current weather in a given location"""
return {
"location": location,
"temperature": "72",
"unit": unit,
"forecast": ["sunny", "windy"],
}
@prompt_chain(
template="What's the weather like in {city}?",
functions=[get_current_weather],
)
async def describe_weather(city: str) -> str:
...
output = await describe_weather("Boston")
```
=> Enable async prompt_chain. Remove FunctionCallMessage

src/magentic/chat_model/function_schemas.py, tests/test_function_schemas.py
Make `AsyncIterableFunctionSchema.serialize_args` raise `NotImplementedError`. It is a sync function so it cannot async-iterate the value passed as input.
=> Make AsyncIterableFunctionSchema.serialize_args raise NotImplementedError

README.md, src/magentic/__init__.py, src/magentic/chat_model/message.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/chatprompt.py, src/magentic/prompt_function.py, tests/test_chatprompt.py
Add a new decorator `@chatprompt` which allows defining a prompt for a chat model consisting of a set of templated chat messages.
Resolves https://github.com/jackmpcollins/magentic/issues/31
Closes https://github.com/jackmpcollins/magentic/pull/27
---
The `@chatprompt` decorator works just like `@prompt` but allows you to pass chat messages as a template rather than a single text prompt. This can be used to provide a system message or for few-shot prompting where you provide example responses to guide the model's output. Format fields denoted by curly braces `{example}` will be filled in all messages - use the `escape_braces` function to prevent a string being used as a template.
```python
from magentic import chatprompt, AssistantMessage, SystemMessage, UserMessage
from …
```
=> Add chatprompt decorator

src/magentic/prompt_chain.py, tests/test_prompt_chain.py
I added an optional max_calls parameter to the prompt_chain decorator in order to limit api calls. By default, when it's not given unlimited calls can be made just like before. If it's given and the limit is reached, a PermissionError is raised.
=> add optional max_calls argument to prompt_chain

README.md, src/magentic/chat_model/openai_chat_model.py, src/magentic/settings.py, tests/test_openai_chat_model.py
Allow setting `max_tokens` param in `OpenaiChatModel`. The default value for this can also be set using an environment variable `MAGENTIC_OPENAI_MAX_TOKENS`.
Example
```python
from magentic import prompt
from magentic.chat_model.openai_chat_model import OpenaiChatModel
@prompt("Hello, how are you?", model=OpenaiChatModel(max_tokens=3))
def test() -> str:
...
test()
```
Fixes https://github.com/jackmpcollins/magentic/issues/44
Also added type hint overloads for `OpenaiChatModel.(a)complete` to make it more correct/specific.
=> Allow setting max_tokens param

README.md, examples/quiz/1_quiz_async.py, src/magentic/backend.py, src/magentic/chat.py, src/magentic/chat_model/base.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/chatprompt.py, src/magentic/prompt_chain.py, src/magentic/prompt_function.py, src/magentic/settings.py, tests/test_backend.py
Create a `ChatModel` abstract base class. Use this for type hints. Others can implement this interface to use other backends/models.
Add a setting for choosing backend (currently just openai).
Resolves https://github.com/jackmpcollins/magentic/issues/32
=> Make backend configurable

src/magentic/chat_model/function_schema.py, src/magentic/typing.py, tests/test_function_schema.py, tests/test_typing.py
Handle pydantic generic BaseModel in `name_type` and `BaseModelFunctionSchema`
Fixes https://github.com/jackmpcollins/magentic/issues/49
Closes https://github.com/jackmpcollins/magentic/pull/51
=> Handle pydantic generic BaseModel in name_type and function schema

README.md, src/magentic/__init__.py, src/magentic/backend.py, src/magentic/chat_model/base.py, tests/test_backend.py, tests/test_prompt_function.py
Allow the chat_model/LLM to be set using a context manager. This allows the same prompt-function to easily be reused with different models, and also makes it neater to dynamically set the model.
```python
from magentic import OpenaiChatModel, prompt
@prompt("Say hello")
def say_hello() -> str:
...
@prompt(
"Say hello",
model=OpenaiChatModel("gpt-4", temperature=1),
)
def say_hello_gpt4() -> str:
...
say_hello()  # Uses env vars or default settings
with OpenaiChatModel("gpt-3.5-turbo"):
say_hello()  # Uses gpt-3.5-turbo due to context manager
say_hello_gpt4()  # Uses gpt-4 with temperature=1 because explicitly configured
```
=> Allow ChatModel to be set with context manager

.github/workflows/test.yml, README.md, poetry.lock, pyproject.toml, src/magentic/backend.py, src/magentic/chat_model/base.py, src/magentic/chat_model/litellm_chat_model.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/settings.py, src/magentic/streaming.py, tests/chat_model/test_litellm_chat_model.py, tests/test_backend.py, tests/test_prompt_function.py
Add support for a `litellm` backend with https://github.com/BerriAI/litellm as an optional dependency.
Also
- Skip tests requiring external services by default
- Fix: do not discard first chunk of streamed responses
=> Add LiteLLM backend

README.md, src/magentic/backend.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/settings.py, tests/chat_model/test_openai_chat_model.py, tests/test_backend.py
Add OpenAI seed param for deterministic sampling. Set this using env var `MAGENTIC_OPENAI_SEED`, or in code with `OpenaiChatModel(..., seed=42)`.
Resolves https://github.com/jackmpcollins/magentic/issues/68
=> Add OpenAI seed param for deterministic sampling

README.md, src/magentic/backend.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/settings.py, tests/chat_model/test_openai_chat_model.py, tests/test_backend.py
- Add api_key param to OpenaiChatModel
- Add MAGENTIC_OPENAI_API_KEY setting
- Include MAGENTIC_OPENAI_API_KEY in readme
Resolves #73
=> Allow setting api_key in OpenaiChatModel

src/magentic/chat_model/base.py, src/magentic/chat_model/litellm_chat_model.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/chatprompt.py, src/magentic/prompt_function.py, tests/test_chatprompt.py, tests/test_prompt_function.py
Resolves https://github.com/jackmpcollins/magentic/issues/79
Add `stop` param to enable stopping token generation, for both `@prompt` and `@chatprompt`.
---
```python
from magentic import prompt
@prompt(
"Say the alphabet",
stop=["G"],
)
def say_alphabet() -> str:
...
say_alphabet()
```
=> Add stop param

src/magentic/chat_model/function_schema.py, tests/test_function_schema.py
Handle functions with *args and **kwargs by serializing these as normal params (list/array for args, dict/object for kwargs), and using the function signature to parse these correctly into the `FunctionCall` when returned by the LLM.
Fixes https://github.com/jackmpcollins/magentic/issues/102
=> Handle functions with *args and **kwargs

pyproject.toml, tests/test_chatprompt.py
Resolve pyright error for return type not being met by adding `...` back to test functions.
Make ruff ignore unnecessary `...`
=> Use Ellipses in functions with docstrings

src/magentic/chat.py, src/magentic/chat_model/message.py, src/magentic/chat_model/openai_chat_model.py, tests/chat_model/test_openai_chat_model.py, tests/test_chatprompt.py
> [!WARNING]  
> Breaking Change: `FunctionResultMessage` init param `function_call: FunctionCall` replaced by `function: Callable`
Only the name of the function is needed when serializing the `FunctionResultMessage` so we do not need the whole `FunctionCall`. This simplifies creating `@chatprompt` function where the chat contains a function call. e.g.
```python
from magentic import (
chatprompt,
AssistantMessage,
UserMessage,
FunctionCall,
FunctionResultMessage,
)
def plus(a: int, b: int) -> int:
return a + b
@chatprompt(
UserMessage("Use the plus function to add 1 and 2."),
AssistantMessage(FunctionCall(plus, 1, 2)),
FunctionResultMessage(3, plus),
)
def do_math() -> str:
...
do_math()
```
Also
- Add test for `message_to_openai_message`
- Fix: function name when serializing …
=> Use function instead of FunctionCall in FunctionResultMessage

src/magentic/chat_model/message.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/chatprompt.py, tests/chat_model/test_message.py, tests/chat_model/test_openai_chat_model.py, tests/test_chatprompt.py
Groundwork for enabling adding more `Message` subclasses, with any formatting logic. This is to support adding message types for gpt4-vision (issue https://github.com/jackmpcollins/magentic/issues/58), and possibly placeholders within these for inserting values more generally than the string formatting currently supported.
- Add `format` method to `Message` class, replacing `with_content`
- Use `singledispatch` for `message_to_openai_message` to allow extending with new `Message` subclasses
Also move some optional openai params to only provide if set
---
Message subclass with custom format method
```python
from typing import Any
from magentic import chatprompt
from magentic.chat_model.message import Message
class UppercaseMessage(Message[str]):
def format(self, **kwargs: Any) -> …
```
=> Add format method to Message. Allow registering new types with message_to_openai_message

docs/formatting.md, mkdocs.yml, src/magentic/formatting.py, tests/test_formatting.py, tests/test_prompt_function.py
- Add `BulletedList`, `NumberedList`, `BulletedDict` and `NumberedDict` classes for formatting.
- Add "formatting" docs page about these classes and how to customize formatting in prompts.
=> Add docs and classes for formatting objects in prompts

docs/vision.md
This is necessary because of [Wikimedia's user-agent policy](https://meta.wikimedia.org/wiki/User-Agent_policy) that results in a 403 being returned rather than an image if a user agent isn't specified. This, in-turn,  causes the example to fail if it is copy-pasted with a `BadRequestError` since the response from Wikimedia is not an image.
Feel free to tweak the comment / User-agent.
=> Docs: Fix bytes vision example

poetry.lock, pyproject.toml, tests/conftest.py, tests/test_prompt_function.py
- Load .env file for tests. This was already happening on import of `litellm`. Now env vars are loaded when running individual tests that did not import litellm.
- Fix flaky return_dict test. GPT3.5 and 4 both struggle to use arbitrary keys in the tool_call. Might in future be better to serialize dict/mapping into an array of key value pairs.
=> Load .env file for tests. Fix flaky return_dict test.

src/magentic/chat_model/openai_chat_model.py
Remove tool_call.type check to fix LiteLLM Mistral tool calling
Resolves https://github.com/jackmpcollins/magentic/issues/152
=> Remove tool_call.type check to fix LiteLLM Mistral tool calling

src/magentic/chat.py, src/magentic/chat_model/litellm_chat_model.py, src/magentic/chat_model/openai_chat_model.py, tests/chat_model/test_openai_chat_model.py, tests/test_backend.py, tests/test_prompt_function.py
- Remove unneeded wrapper functions for openai and litellm completion
- Use new `discard_none_arguments` to remove None args
- Create `STR_OR_FUNCTIONCALL_TYPE` to have single source for these
- Include fixes for (mostly) working with Mistral from PR #164 
- Fix `Chat` to maintain unset `model` attribute through method calls
=> Remove unneeded wrapper functions for openai and litellm completion

docs/vision.md, src/magentic/chat_model/anthropic_chat_model.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/function_call.py, src/magentic/settings.py, tests/test_prompt_function.py
Set default LLM to gpt-4-turbo. Update vision docs.
Also fix
- tool id must be less than 29 chars for openai
- flake test `test_decorator_return_pydantic_model`
Now we can get structured outputs straight from vision 🎉 
```python
from pydantic import BaseModel, Field
from magentic import chatprompt, UserMessage
from magentic.vision import UserImageMessage
IMAGE_URL_WOODEN_BOARDWALK = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
class ImageDetails(BaseModel):
description: str = Field(description="A brief description of the image.")
name: str = Field(description="A short name.")
@chatprompt(
UserMessage("Describe the following image in one sentence."), …
```
=> Set default LLM to gpt-4-turbo. Update vision docs.

src/magentic/chat_model/anthropic_chat_model.py, src/magentic/chat_model/base.py, src/magentic/chat_model/litellm_chat_model.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/streaming.py, tests/chat_model/test_litellm_chat_model.py, tests/test_streaming.py
- Add truncate method to StreamedStr
- DRY up str return type creation + validation / error message
Error now looks like
```
StructuredOutputError: String was returned by model but not expected. You may need to update your prompt to encourage the model to return a specific type. Model output: '{ "name": "return_list_of_int", "arguments": { "properties": { "value": { "items": [1, 2, 3], [...]'
```
=> Include generated text in error message for "string not expected"

poetry.lock, pyproject.toml, src/magentic/chat_model/openai_chat_model.py, tests/chat_model/test_anthropic_chat_model.py, tests/chat_model/test_openai_chat_model.py, tests/test_prompt_function.py
Use tool_choice "required" for OpenaiChatModel when a string output is not present in the return types. This eliminates `StructuredOutputError`!
=> Use tool_choice required for OpenaiChatModel

src/magentic/chat_model/function_schema.py, tests/test_function_schema.py, tests/test_prompt_function.py
Use `model_construct` to skip validation on serialization
Resolves #211
=> Skip validation for message serialization

poetry.lock, pyproject.toml, src/magentic/chat_model/anthropic_chat_model.py, tests/chat_model/test_anthropic_chat_model.py
- Bump Anthropic version to https://github.com/anthropics/anthropic-sdk-python/releases/tag/v0.26.0 to support tool_choice, streamed tool calls, and vision
- Update `AnthropicChatModel` to use streaming to support `StreamedStr`
Currently object streaming does not work due to arrays in tool calls not being streamed. Anthropic issue: https://github.com/anthropics/anthropic-sdk-python/issues/509
```python
from magentic import prompt, StreamedStr
from magentic.chat_model.anthropic_chat_model import AnthropicChatModel
@prompt(
"Tell me about {topic}.",
model=AnthropicChatModel("claude-3-opus-20240229"),
)
def tell_me_about(topic: str) -> StreamedStr: ...
for chunk in tell_me_about("chocolate"):
print(chunk, end="", flush=True)
```
=> Switch AnthropicChatModel to use streaming

poetry.lock, pyproject.toml, src/magentic/chat_model/anthropic_chat_model.py, src/magentic/chat_model/function_schema.py, src/magentic/chat_model/message.py, src/magentic/chat_model/mistral_chat_model.py, src/magentic/chat_model/openai_chat_model.py, tests/chat_model/test_anthropic_chat_model.py, tests/chat_model/test_message.py, tests/chat_model/test_mistral_chat_model.py, tests/chat_model/test_openai_chat_model.py
Resolves #74 
- Create new `Usage` class
- Add this as an optional attribute of `AssistantMessage`
- Wrap openai/anthropic response stream to set usage when encountered
Example of non-streamed response with usage immediately available
```python
from magentic import OpenaiChatModel, UserMessage
chat_model = OpenaiChatModel("gpt-3.5-turbo", seed=42)
message = chat_model.complete(messages=[UserMessage("Say hello!")])
print(message.usage)
```
Example of streamed response where usage only becomes available after the stream has been processed
```python
from magentic import OpenaiChatModel, UserMessage
from magentic.streaming import StreamedStr
chat_model = OpenaiChatModel("gpt-3.5-turbo", seed=42)
message = chat_model.complete(messages=[UserMessage("Say hello!")], output_types=[StreamedStr]) …
```
=> Return usage stats on AssistantMessage

src/magentic/chat_model/mistral_chat_model.py, src/magentic/chat_model/openai_chat_model.py
Closes #240 
> Use `parallel_tool_calls: false` to force a single function call from OpenAI when `ParallelFunctionCall` return type is not present.
>
> Introduced in https://github.com/openai/openai-python/releases/tag/v1.32.0
>
> docs: https://platform.openai.com/docs/guides/function-calling/parallel-function-calling
=> Use new `parallel_tool_calls` arg with OpenAI API

src/magentic/function_call.py, tests/chat_model/test_mistral_chat_model.py
Limit tool call id to 9 chars for Mistral.
Fixes #276 
Closes #277
=> Limit tool call id to 9 chars for Mistral

docs/function-calling.md, docs/structured-outputs.md, poetry.lock, pyproject.toml, src/magentic/__init__.py, src/magentic/_pydantic.py, src/magentic/chat_model/function_schema.py, tests/chat_model/test_openai_chat_model.py, tests/test_function_schema.py
- Extend pydantic's `ConfigDict` to add `openai_strict: bool`
- Enable pydantic config to be set on functions
- For all types, pass along the pydantic config (if present) to the pydantic model used for serialization in FunctionSchemas
- Try read pydantic config when converting type to JSON schema, and use openai strict converter if `openai_strict` is True
- Add to docs
Example
```python
from magentic import prompt, ConfigDict
from pydantic import BaseModel
class Superhero(BaseModel):
model_config = ConfigDict(openai_strict=True)
name: str
age: int
power: str
enemies: list[str]
@prompt("Create a Superhero named {name}.")
def create_superhero(name: str) -> Superhero: ...
create_superhero("Garden Man")
```
See docs for more: http://localhost:8000/structured-outputs/#configdict
Related to …
=> Add support for OpenAI structured outputs

CONTRIBUTING.md, Makefile, pyproject.toml, uv.lock
Add `CONTRIBUTING.md` and Makefile adapted from those from pydantic Logfire
- https://github.com/pydantic/logfire/blob/267c83a5b91fff6a05955608cd0f83b58a504126/CONTRIBUTING.md
- https://github.com/pydantic/logfire/blob/267c83a5b91fff6a05955608cd0f83b58a504126/Makefile
Also generate html coverage report
=> Add CONTRIBUTING.md

Makefile, pyproject.toml, src/magentic/function_call.py, tests/cassettes/test_chatprompt/test_chatprompt_readme_example.yaml, tests/cassettes/test_chatprompt/test_chatprompt_with_function_call_and_result.yaml, tests/cassettes/test_prompt_chain/test_async_prompt_chain.yaml, tests/cassettes/test_prompt_chain/test_prompt_chain.yaml, tests/cassettes/test_vision/test_chatprompt_with_user_image_message.yaml, tests/chat_model/cassettes/test_mistral_chat_model/test_mistral_chat_model_few_shot_prompt.yaml, tests/chat_model/test_message.py, tests/conftest.py, tests/test_vision.py, uv.lock
- Make VCR match on request body
- Mock `_create_unique_id` to make it deterministic in tests
- Change usage of deprecated `gpt-4-vision-preview` to `gpt-4o`
=> Make VCR match on request body in tests

CONTRIBUTING.md, Makefile
Thanks to https://dwmkerr.com/makefile-help-command/
=> Add make help command

.gitignore, Makefile, docs/streaming.md, docs/structured-outputs.md, pyproject.toml, src/magentic/__init__.py, src/magentic/_parsing.py, src/magentic/_streamed_response.py, src/magentic/chat_model/anthropic_chat_model.py, src/magentic/chat_model/base.py, src/magentic/chat_model/function_schema.py, src/magentic/chat_model/litellm_chat_model.py, src/magentic/chat_model/mistral_chat_model.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/chat_model/stream.py, src/magentic/streaming.py, tests/chat_model/cassettes/test_anthropic_chat_model/test_anthropic_chat_model_acomplete_async_parallel_function_call.yaml, tests/chat_model/cassettes/test_anthropic_chat_model/test_anthropic_chat_model_acomplete_async_streamed_response.yaml, tests/chat_model/cassettes/test_anthropic_chat_model/test_anthropic_chat_model_complete_no_structured_output_error.yaml, tests/chat_model/cassettes/test_anthropic_chat_model/test_anthropic_chat_model_complete_parallel_function_call.yaml, tests/chat_model/cassettes/test_anthropic_chat_model/test_anthropic_chat_model_complete_streamed_response.yaml, tests/chat_model/cassettes/test_openai_chat_model/test_openai_chat_model_acomplete_async_streamed_response.yaml, tests/chat_model/cassettes/test_openai_chat_model/test_openai_chat_model_complete_streamed_response.yaml, tests/chat_model/test_anthropic_chat_model.py, tests/chat_model/test_openai_chat_model.py, tests/conftest.py, tests/test_streaming.py, uv.lock
Add `StreamedResponse` and `AsyncStreamedResponse` types for returning a combination of `StreamedStr` and `FunctionCall`.
Closes #220 
Closes #232 
Closes #226 
Also
- set the `disable_parallel_tool_use` for Anthropic
- add make command to visualize import graph using pydeps
- Fix bug with .env env var loading in tests
- Fix bug with consuming unconsumed groups in `OutputStream`
---
Some LLMs have the ability to generate text output and make tool calls in the same response. This allows them to perform chain-of-thought reasoning or provide additional context to the user. In magentic, the `StreamedResponse` (or `AsyncStreamedResponse`) class can be used to request this type of output. This object is an iterable of `StreamedStr` (or `AsyncStreamedStr`) and `FunctionCall` instances.
!!! …
=> Add `(Async)StreamedResponse` for multi-part responses

docs/streaming.md, docs/structured-outputs.md, src/magentic/chat_model/stream.py, src/magentic/streaming.py, tests/chat_model/test_anthropic_chat_model.py, tests/chat_model/test_openai_chat_model.py
Consume any remaining chunks via `StreamedStr` or output object in `OutputStream` so that internal caching in these objects can be used.
This removes the need to process StreamedStr immediately when it is received, so I removed the warning from the docs.
=> Consume LLM output stream via returned objects to allow caching

pyproject.toml, src/magentic/chat_model/anthropic_chat_model.py, src/magentic/chat_model/base.py, src/magentic/chat_model/litellm_chat_model.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/chat_model/retry_chat_model.py, src/magentic/chat_model/stream.py, src/magentic/chatprompt.py, src/magentic/function_call.py, src/magentic/prompt_chain.py, src/magentic/prompt_function.py, src/magentic/typing.py, tests/test_backend.py
- Add split-on-trailing-comma for imports
- Remove need to comment "noqa: S101" on asserts in code
=> Improve ruff format/lint rules

src/magentic/chat.py
The initializer directly invokes `list` on `messages` anyway, and the other parameters are generic too.
=> Accept Sequence[Message] instead of list for Chat

pyproject.toml, src/magentic/chat_model/litellm_chat_model.py, src/magentic/chat_model/openai_chat_model.py, uv.lock
ChatCompletionStreamState was made public in https://github.com/openai/openai-python/releases/tag/v1.56.0 so switch to using that.
related issue: https://github.com/openai/openai-python/issues/1833
=> Use public import for ChatCompletionStreamState

src/magentic/chat_model/openai_chat_model.py, tests/cassettes/test_chatprompt/test_chatprompt_readme_example.yaml, tests/cassettes/test_chatprompt/test_chatprompt_with_function_call_and_result.yaml, tests/cassettes/test_prompt_chain/test_async_prompt_chain.yaml, tests/cassettes/test_prompt_chain/test_prompt_chain.yaml, tests/chat_model/cassettes/test_mistral_chat_model/test_mistral_chat_model_few_shot_prompt.yaml, tests/chat_model/test_openai_chat_model.py
Remove the `"content": None,` from openai messages because it seems to be no longer needed as flagged by @alexchandel in https://github.com/jackmpcollins/magentic/issues/389#issuecomment-2552729053
=> Remove unused content None from openai messages

docs/function-calling.md, src/magentic/prompt_chain.py, tests/cassettes/test_prompt_chain/test_async_prompt_chain.yaml, tests/cassettes/test_prompt_chain/test_async_prompt_chain_messages.yaml, tests/cassettes/test_prompt_chain/test_prompt_chain.yaml, tests/cassettes/test_prompt_chain/test_prompt_chain_messages.yaml, tests/test_prompt_chain.py
Also update docs for this.
Closes #389 
Closes #391 
Closes #392 
Thanks to @alexchandel for the suggestion!
Example
```python
from magentic import prompt_chain, UserMessage
def get_current_weather(location, unit="fahrenheit"):
"""Get the current weather in a given location"""
return {"temperature": "72", "forecast": ["sunny", "windy"]}
@prompt_chain(
template=[UserMessage("What's the weather like in {city}?")],
functions=[get_current_weather],
)
def describe_weather(city: str) -> str: ...
describe_weather("Boston")
'The weather in Boston is currently 72°F with sunny and windy conditions.'
```
=> Allow Messages as input to prompt_chain

src/magentic/chat_model/anthropic_chat_model.py, tests/chat_model/test_anthropic_chat_model.py
Adds magentic message to anthropic message converter for streamed responses. 
Please let me know if this needs tests.
=> add msg-to-anthropic-msg converter for streamedresponse

src/magentic/chat_model/function_schema.py, tests/test_function_schema.py
When the arguments string is empty, replace it with an empty json dict, so pydantic can parse it correctly.
Fixes #407
=> fix - function call with no args when using anthropic api

src/magentic/chat_model/litellm_chat_model.py, tests/chat_model/cassettes/test_litellm_chat_model/test_litellm_chat_model_extra_headers.yaml, tests/chat_model/test_litellm_chat_model.py
My ollama instance runs behind an reverse proxy (Cloudflare Access) which uses custom headers (cf-access-client-id / cf-access-client-secret or cf-access-token) to authenticate the user. I'm able to access my instance using litellm in the following way, but I'd like to switch to using magnetic.
```python
import litellm
response = litellm.completion(
model="ollama/deepseek-coder-v2",
messages=[{"content": "generate a simple sql query", "role": "user"}],
api_base="...",
extra_headers={"cf-access-token": "..."},
)
print(response)
```
closes #260
=> feat: support for passing extra_headers to LitellmChatModel

src/magentic/chat_model/function_schema.py, tests/test_function_schema.py
If the model returned `{"b": 2}` to call function
```python
def plus_with_defaults(a: int = 1, b: int = 1):
return a + b
```
then this would be called as `plus_with_defaults(2)` rather than `plus_with_defaults(b=2)`.
This PR make keyword args preferred if `*args` is not present or not used.
=> Fix: function call parsing positional args ignoring arg defaults
