jackmpcollins/magentic

.github/workflows/publish.yml
Add a github workflow for publishing the package to PyPI when a new release is created.
=> Add publish github workflow

src/magentic/chat_model/openai_chat_model.py
Use pydantic models for OpenAI inputs/outputs. Enables autocompletion in IDE and validates format is correct.
=> Use pydantic models for OpenAI inputs/outputs

README.md
Add missing imports and definition of `Superhero` model.
=> Fix object streaming example in README

src/magentic/chat.py, src/magentic/chat_model/base.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/function_call.py, src/magentic/prompt_chain.py, src/magentic/prompt_function.py, src/magentic/streaming.py
=> Add docstrings where useful

examples/chain_of_verification/chain_of_verification.ipynb
Add example notebook for Chain of Verification
paper: https://arxiv.org/abs/2309.11495
=> Add example notebook for Chain of Verification

src/magentic/chat_model/function_schemas.py, tests/test_function_schemas.py
Handle Iterable type with no item type
=> Handle Iterable type with no item type

src/magentic/chat_model/function_schemas.py, src/magentic/chat_model/openai_chat_model.py, tests/test_function_schemas.py
- Handle BaseModel parameters in functions
- Use function schemas to serialize FunctionResultMessage
=> Handle BaseModel parameters in functions

README.md
- Make object streaming h3
- Tidy env var table
- Add Asyncio section to README
=> Add Asyncio section to README

tests/test_prompt_function.py
=> Make openai tests less flaky

README.md
- Add OPENAI_API_BASE env var to readme
- Mention default values in config section in README
- Add note re setting OPENAI_API_BASE
=> Add instructions for setting OPENAI_API_BASE

.github/workflows/test.yml, poetry.lock
Run `poetry update`, keeping `pydantic<=2.1.0` - to be resolved in PR https://github.com/jackmpcollins/magentic/pull/91
=> Run poetry update

.github/workflows/test.yml, poetry.lock, pyproject.toml, tests/test_chatprompt.py, tests/test_prompt_function.py
Add ruff to pyproject.toml so that version is pinned.
Update ruff to latest version
- Update config key names
- Run ruff to get latest fixes
=> Add ruff to pyproject.toml. Update ruff.

poetry.lock, tests/test_function_schema.py
Update dependencies
Closes https://github.com/jackmpcollins/magentic/pull/113
Closes https://github.com/jackmpcollins/magentic/pull/112
Closes https://github.com/jackmpcollins/magentic/pull/111
Closes https://github.com/jackmpcollins/magentic/pull/91
=> poetry update

src/magentic/chat.py, src/magentic/prompt_chain.py, tests/test_chat.py
Add last_message property to Chat. This is accessed frequently so nice to have tab completion for it.
=> Add last_message property to Chat

poetry.lock, pyproject.toml, src/magentic/chat_model/litellm_chat_model.py, src/magentic/chat_model/openai_chat_model.py, tests/chat_model/test_litellm_chat_model.py
- Bump minimum litellm version to `1.33.7` for anthropic tool call fix https://github.com/BerriAI/litellm/issues/2644#issuecomment-2016320216
- Fix tool call response parsing to handle getting single chunk containing whole message - litellm gives a single message instead of a stream of chunks.
- Add more test coverage for litellm + anthropic (issue #154 )
Resolves: https://github.com/jackmpcollins/magentic/issues/153
=> Fix: LiteLLM Anthropic async tool calls

.github/dependabot.yml
Ignore patch versions in dependabot yml
=> Make dependabot ignore patch version updates

.github/workflows/test.yml
Add options for running the live tests against anthropic and openai APIs. GitHub secrets have been added.
=> Add github workflow options to run existing live tests

docs/function-calling.md, docs/structured-outputs.md, mkdocs.yml, tests/test_function_schema.py
- Add Structured Output docs
- Add section on Annotated/Field to function-calling
- Add test for BaseModel with Field
=> Add Structured Output docs

README.md, docs/configuration.md, docs/index.md, src/magentic/chat_model/anthropic_chat_model.py, src/magentic/chat_model/litellm_chat_model.py
- Highlight features and improve links
- Show `@chaprompt` in README/overview
- Make configuration page clearer
=> Tidy up docs

README.md, docs/function-calling.md, docs/index.md
- Add easier to follow example
- Reorder function calling docs page to start with example
=> Improve function calling docs

.github/workflows/test.yml, README.md, docs/configuration.md, pyproject.toml, src/magentic/backend.py, src/magentic/chat_model/mistral_chat_model.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/settings.py, tests/chat_model/test_mistral_chat_model.py, tests/test_backend.py
- Add `MistralChatModel` built around `OpenaiChatModel`
- Update `OpenaiChatModel` to allow subclasses to override tool_choice argument, and to handle receiving all tool calls in a single chunk
- Update docs to add mistral backend
Resolves #163
=> Add Mistral backend

README.md, docs/configuration.md, poetry.lock, pyproject.toml, tests/chat_model/test_litellm_chat_model.py
Bump litellm dep to >=1.36.0 https://github.com/BerriAI/litellm/releases/tag/v1.36.0 which has a fix for parsing ollama streamed tool calls https://github.com/BerriAI/litellm/pull/3469
Update tests for ollama to include structured outputs
Resolves https://github.com/jackmpcollins/magentic/issues/194
Resolves https://github.com/jackmpcollins/magentic/issues/199
=> Support ollama structured outputs / function calling

README.md, docs/index.md
=> docs: update README.md

docs/vision.md, src/magentic/settings.py, tests/test_prompt_function.py
Make GPT-4o the default OpenAI model
=> Make GPT-4o the default OpenAI model

pyproject.toml, tests/chat_model/test_litellm_chat_model.py
Add tests for LiteLLM async callbacks
=> Add tests for LiteLLM async callbacks

poetry.lock, pyproject.toml, src/magentic/chat_model/anthropic_chat_model.py
With Anthropic 0.28.1 tools and types are no more under beta
=> Update anthropic_chat_model.py to conform with latest anthropic package

README.md, docs/configuration.md, src/magentic/__init__.py, src/magentic/chatprompt.py, src/magentic/function_call.py, src/magentic/logger.py, src/magentic/prompt_chain.py, src/magentic/prompt_function.py, src/magentic/settings.py
- Set up logger
- Add `MAGENTIC_VERBOSE` setting to log to stdout
- Log calls to decorated functions and FunctionCalls
Relates to #55
=> Add basic logging and MAGENTIC_VERBOSE env var

poetry.lock, pyproject.toml, src/magentic/chat_model/litellm_chat_model.py, tests/test_prompt_function.py
Two tests were failing due to Claude returning a chain-of-thought response. The tool_choice param was not being put to best use on the LitellmChatModel to combat this.
=> Fix LitellmChatModel tool_choice parameter to force Anthropic tool use

docs/chat-prompting.md, src/magentic/__init__.py, src/magentic/chat_model/anthropic_chat_model.py, src/magentic/chat_model/message.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/function_call.py, src/magentic/vision.py, tests/chat_model/test_message.py, tests/chat_model/test_openai_chat_model.py, tests/test_chat.py, tests/test_chatprompt.py
- Make `Message` inherit from pydantic `BaseModel`
- Add `ToolResultMessage` parent of `FunctionResultMessage` which is easier to deserialize (taken from #288 )
- Update tests to deal with tool_call_id being considered when checking `FunctionResultMessage` equality
- Add `AnyMessage` that can be used as a return type to generate `Message` objects
- Tests and docs for `AnyMessage`
TODO
- (release notes) docs for `FunctionCall` vs `FunctionResultMessage` equality behavior
- (future) Example notebook showing chat history summary using `AnyMessage`
Fixes #289 
Relates to #287 
---
Example of GPT4o simulating a chat
```python
from magentic import AnyMessage, prompt
@prompt("Create an example of few-shot prompting for a chatbot")
def make_few_shot_prompt() -> list[AnyMessage]: ... …
```
=> Make Message a pydantic model / serializable

docs/vision.md, src/magentic/chat_model/anthropic_chat_model.py, src/magentic/chat_model/openai_chat_model.py, src/magentic/vision.py, tests/test_vision.py
Add Anthropic vision
Closes #250
=> Add Anthropic vision

.pre-commit-config.yaml
=> Update precommit hooks

src/magentic/chat_model/anthropic_chat_model.py, src/magentic/chat_model/openai_chat_model.py, tests/chat_model/test_anthropic_chat_model.py, tests/chat_model/test_openai_chat_model.py
So assistant messages in an async `Chat` can be serialized to generate the next response
=> Support AsyncParallelFunctionCall in message_to_X_message
